-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 31, 2017 at 12:57 PM
-- Server version: 5.5.49-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `comicsnews`
--
CREATE DATABASE IF NOT EXISTS `comicsnews` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `comicsnews`;

-- --------------------------------------------------------

--
-- Table structure for table `noticia`
--

CREATE TABLE IF NOT EXISTS `noticia` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(100) NOT NULL,
  `descricao` text NOT NULL,
  `img` varchar(100) NOT NULL,
  `data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `autor` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=57 ;


--
-- Extraindo dados da tabela `noticia`
--

INSERT INTO `noticia` (`ID`, `titulo`, `descricao`, `img`, `data`, `autor`) VALUES
(4, 'oijjhnhjkl', 'ijok	', '17553601_999948616802707_8207016520846846175_n.jpg', '2017-04-01 20:19:35', 'aaauhjhj'),
(5, 'testeuh', 'banco imagem	', '20170222_130931.jpg', '2017-04-01 21:11:45', 'teste salvar arquivo'),
(6, 'testeuh2', 'banco imagem	2222', '20170222_130931.jpg', '2017-04-01 21:13:11', 'teste salvar arquivo2'),
(7, 'PPHP', 'DDDDD	', '17553601_999948616802707_8207016520846846175_n.jpg', '2017-04-02 01:13:41', 'TESTE PHP'),
(8, 'ededeeded', '	dedede', '17458007_1610804642267233_3774514461344861159_n.jpg', '2017-04-02 02:51:20', 'swdede'),
(9, 'ededeeded', '	dedede', '17458007_1610804642267233_3774514461344861159_n.jpg', '2017-04-02 02:53:26', 'swdede'),
(10, 'Para 45% dos brasileiros, trabalhar de casa aumenta a produtividade', '			    			    			    O sal?rio deixou de ser o fator mais importante para os brasileiros na busca por um novo emprego. O estudo ?Trabalhador Digital?, realizado pela Citrix, revela que para 34% dos entrevistados, a flexibilidade de hor?rio e o fato de trabalhar pr?ximo de casa s?o fatores que pesam mais para essa decis?o. A remunera??o ? apontada por 14% dos participantes como a motiva??o principal.\r\n\r\nO objetivo do estudo era entender os aspectos valorizados em um emprego e saber a opini?o das pessoas sobre a mobilidade como parte de uma nova din?mica de trabalho. Um total de 77% dos entrevistados trabalha com pessoas que se encontram em outros escrit?rios ou cidades. Nesse sentido, colaborar de forma remota com colegas de empresa torna desnecess?rio o deslocamento f?sico para a execu??o das atividades. O aumento da produtividade ? apontado com um dos principais benef?cios do trabalho remoto por quase metade dos participantes: 45% acreditam que sua produtividade aumentaria se pudessem realizar seu trabalho em casa.\r\n\r\nMobilidade corporativa com seguran?a\r\n\r\nTrabalhar de casa ou de qualquer lugar ? uma possibilidade cada dia mais real para muitos, mas h? o receio de empregadores quanto ? seguran?a das informa??es trafegando fora do escrit?rio. O estudo buscou compreender tamb?m qual o entendimento dos profissionais de uma empresa quanto ?s pol?ticas de seguran?a. No Brasil, 56% acham essas pol?ticas restritivas, mas, mesmo assim, 88% acessam os dados corporativos por meio de dispositivos permitidos.			  			  			  ', '15823201_1128929200539775_4814580229153134022_n.jpg', '2017-04-02 15:57:10', 'Alterado Junioreee'),
(11, 'Para 45% dos brasileiros, trabalhar de casa aumenta a produtividade', '			    			    O sal?rio deixou de ser o fator mais importante para os brasileiros na busca por um novo emprego. O estudo ?Trabalhador Digital?, realizado pela Citrix, revela que para 34% dos entrevistados, a flexibilidade de hor?rio e o fato de trabalhar pr?ximo de casa s?o fatores que pesam mais para essa decis?o. A remunera??o ? apontada por 14% dos participantes como a motiva??o principal.\r\n\r\nO objetivo do estudo era entender os aspectos valorizados em um emprego e saber a opini?o das pessoas sobre a mobilidade como parte de uma nova din?mica de trabalho. Um total de 77% dos entrevistados trabalha com pessoas que se encontram em outros escrit?rios ou cidades. Nesse sentido, colaborar de forma remota com colegas de empresa torna desnecess?rio o deslocamento f?sico para a execu??o das atividades. O aumento da produtividade ? apontado com um dos principais benef?cios do trabalho remoto por quase metade dos participantes: 45% acreditam que sua produtividade aumentaria se pudessem realizar seu trabalho em casa.\r\n\r\nMobilidade corporativa com seguran?a\r\n\r\nTrabalhar de casa ou de qualquer lugar ? uma possibilidade cada dia mais real para muitos, mas h? o receio de empregadores quanto ? seguran?a das informa??es trafegando fora do escrit?rio. O estudo buscou compreender tamb?m qual o entendimento dos profissionais de uma empresa quanto ?s pol?ticas de seguran?a. No Brasil, 56% acham essas pol?ticas restritivas, mas, mesmo assim, 88% acessam os dados corporativos por meio de dispositivos permitidos.			  			  ', '', '2017-04-02 21:27:53', 'Carlos Junior'),
(12, 'nkn', 'kmm			  ', 'erro3.jpg', '2017-04-02 22:21:51', 'asasadd'),
(13, 'çç', 'çç~ç			  ', 'ccxp.jpg', '2017-04-02 22:44:15', 'll'),
(14, 'Comics', 'Fãs e admiradores da cultura pop no Recife tiveram, neste domingo (26), um motivo especial para ir ao Marco Zero, no Centro da capital pernambucana. Além de conhecer quadrinistas que trabalham para grandes produtoras como a Marvel e a DC Comics, o público também teve a oportunidade de conhecer e, de quebra, exibir o visual dos personagens preferidos através de cosplays.\r\n“Vim porque gosto muito de cosplays e porque queria mostrar o meu visual. Admiro essa personagem e gosto muito da personalidade dela”, conta a estudante Lilian Cavalcanti, 18, vestida de Kurumi, do anime Date a Live. Mesmo com o sol forte da tarde, jovem não foi a única a caprichar no figurino para ir ao evento.', 'ccxp.jpg', '2017-04-02 22:45:09', 'Fabricia'),
(15, 'Comic Con é realizada', 'Primeira edição da feira de cultura pop Comic Con realizada na Arábia Saudita está provocando polêmica no país, onde muitos o consideraram um evento "indecente" e um convite à "depravação" dos jovens.\r\nO festival dedicado aos videogames, às séries de televisão e à cultura popular em geral foi realizado entre 16 e 18 de fevereiro na cidade de Jidá, apesar da oposição dos círculos religiosos conservadores.\r\n"A indecência, a mistura com as mulheres de muçulmanos, a dança e a música não podem ser considerados entretenimento, senão um convite à depravação e ao pecado", disse Tamin (@m_1385), usuário do Twitter.\r\nO festival faz parte de uma iniciativa do governo para oferecer mais opções de entretenimento para os jovens menores de 25 anos, que representam mais da metade da população deste país regido por uma visão rigorista do Islã, onde a segregação entre homens e mulheres é obrigatória.', '102114811-457095424.530x298.jpg', '2017-04-02 22:47:22', 'Fab Galibi'),
(16, 'Coleção com mais de 18 mil', 'Uma coleção de mais de 18 mil histórias em quadrinhos raras e 300 peças relacionadas vai ser leiloada a partir de 15 de março. A coleção pertence a Jon Berk, um advogado do estado americano de Connecticut.\r\nO acervo vai ficar exposto na galeria Metropolis, em Nova York, e irá a leilão online 4 dias depois.', 'comics.jpg', '2017-04-02 22:50:05', 'Carlos Simões'),
(17, 'Ilustrador da Marvel e da DC', 'O ilustrador pernambucano da Marvel e da DC Comics, Thony Silas, resolveu usar seu dom para criar um jovem super-herói com câncer. Careca e vestindo um imponente uniforme azul e dourado, Gael foi desenvolvido para representar a luta das crianças contra a doença. O artista se sensibilizou com a causa após visitar o Grupo de Ajuda à Criança Carente com Câncer em Pernambuco (GAC-PE), no Recife.\r\nGael é cheio de detalhes e foi criando para inspirar os pequenos, que precisam enfrentar uma dura realidade ainda tão jovens. A inspiração do personagem veio em agosto do ano passado. Sem nenhuma pretensão, Thony conta que tudo começou ao visitar a instituição como voluntário.\r\n“Eu já tinha em mente desenhar cada um com roupinha do super-herói favorito, mas enquanto desenhava uma das crianças, o João Gabriel, um garoto fantástico, muito expressivo e de um sorriso ímpar, saiu com a ideia de que eles também poderiam ser super-heróis. Foi ele falar que em poucos minutos a ideia já estava borbulhando na minha mente”, relembra.			  ', 'mascote2_4.jpg', '2017-04-02 22:51:05', 'Fabricia'),
(18, 'Cosplay de Coragem', 'Um casal de Itabaiana, no Agreste paraibano, foi classificado entre 12 finalistas e vai representar a Paraíba no concurso de cosplay da Comic Con Experience (CCXP) 2016, que começa nesta quinta-feira (1º), em São Paulo. Vestidos como os personagens Eustácio e Muriel, donos do cão "Coragem", do desenho animado de mesmo nome, os aposentados Albani e Carlos Paiva, de 56 e 65 anos, respectivamente, têm chamado atenção em eventos de cultura pop do Nordeste.', 'muriel.jpg', '2017-04-02 22:53:37', 'Fabrícia Galibi'),
(19, 'Moana', 'Neste sábado (3), a Comic Con Experience foca atenções de seu auditório principal a grandes atrações do cinema. Ao mesmo tempo, seu espaço secundário recebe nomes populares de séries e dos quadrinhos. Os ingressos para este terceiro dia estão esgotados.\r\nEntre os destaques do dia, estão a exibição da nova e aguardada animação da Disney, atores de grandes sagas geeks e parte do elenco de um dos grandes lançamentos de 2017. O evento acontece no São Paulo Expo, na Zona Sul da capital paulista, até o domingo (4).\r\nA atriz Evanna Lynch, conhecida por interpretar a jovem Luna Lovegood na série de filmes de "Harry Potter", abre os trabalhos do auditório Cinemark. Enquanto isso, no auditório Ultra, o ator David Ramsey, que interpreta John Diggle em "Arrow", fala sobre os bastidores na série', 'ccxp-dia-2.jpg', '2017-04-02 22:55:22', 'Fabrícia'),
(20, 'Ben Affleck', 'Ben Affleck disistiu de dirigir o próximo filme do Batman, que está sendo preparado pelo estúdio Warner Bros., informou na segunda-feira (30) a "Variety". De acordo com a revista, ele vai trabalhar apenas como ator e produtor do longa.\r\nEm princípio estava previsto que Affleck fosse o diretor e protagonista do novo longa-metragem do Homem-Morcego, mas há algumas semanas circulavam rumores em Hollywood que o artista somente atuaria no filme.', 'batmanvsuperman.jpg', '2017-04-02 22:56:57', 'Maria Sousa'),
(21, 'Pernambuco vai receber', 'O Centro de Convenções de Pernambuco, em Olinda, vai receber a primeira edição fora de São Paulo da Comic Con Experience (CCXP), feira de quadrinhos, séries de TV, cinema e games. O evento recebeu o nome de CCXP Tour Nordeste e está marcado para acontecer entre os dias 13 e 16 de abril de 2017. O anúncio foi feito nesta quinta-feira (15), durante evento no Teatro Guararapes, em Olinda.\r\nA edição pernambucana da Comic Con é organzida pelo mesmo grupo que faz a de São Paulo, que inclui o Omelete Group, Chiaroscuro Studios e Pizzitoys), em parceria com o Governo do Estado de Pernambuco. A expectativa é receber entre 60 e 80 mil visitantes, segundo os organizadores.\r\nA programação vai contar com lojas oficiais da Warner, Iron Studios, Social Comics, Loja Mundo Geek e Omelete Box. Os produtores afirmam ainda que há negociações avançadas com grandes estúdios e outras lojas oficiais de marcas relacionados a cultura pop.', 'cosplayers.jpg', '2017-04-02 22:58:39', 'José Silva'),
(22, 'Vin Diesel', 'O ator Vin Diesel ("Velozes e furiosos") virá ao Brasil para participar da Comic Con Experience (CCXP), anunciou a Paramount nesta quarta-feira (16).\r\nO astro estará ao lado das atrizes Ruby Rose ("Orange is the New Black") e Nina Dobrev ("The Vampire Diaries") para participar do painel do filme "xXx: Reativado", que estreia no Brasil em 19 de janeiro de 2017. O evento está marcado para acontecer no dia 1º de dezembro, às 15h30.\r\n"xXx: Reativado" é o terceiro filme da série "Triplo X", que teve Vin Diesel na primeira parte e o rapper e ator Ice Cube na segunda. A produção traz de volta Xander Cage (Diesel), atleta radical que virou agente do governo, em uma corrida para recuperar uma arma aparentemente invencível conhecida como Caixa de Pandora. O jogador brasileiro Neymar Jr. participa do filme.\r\nA CCXP acontece no São Paulo Expo, na Zona Sul da capital paulista, entre os dias 1º e 4 de dezembro. Outros convidados internacionais já confirmados para o evento incluem James Gunn, diretor de "Guardiões da Galáxia", Natalie Dormer, da série "Game of Thrones", e Milla Jovovich, dos filmes de "Resident Evil".			  ', '2016-01-07t031124z_21073_tb3ec1708uqkx_rtrmadp_3_awards-peopleschoice.jpg', '2017-04-02 23:00:10', 'Fabrícia Galibi'),
(23, 'Milla Jovovich', 'A atriz Milla Jovovich ("O quinto elemento") e o diretor Paul W. S. Anderson, que dirigiu e produziu os filmes baseados nos games da série "Resident Evil", virão ao Brasil para participar da Comic Con Experience (CCXP), anunciou a Sony nesta segunda-feira (14).\r\nNa feira de cultura pop, eles vão discutir sobre o filme "Resident Evil 6: O capítulo final", que tem estreia prevista no Brasil para 26 de janeiro de 2017. O painel está marcado para acontecer no dia 2 de dezembro, às 13h30.\r\nA CCXP acontece no São Paulo Expo, na Zona Sul da capital paulista, entre os dias 1º e 4 de dezembro. Outros convidados internacionais já confirmados para o evento incluem James Gunn, diretor de "Guardiões da Galáxia", e Natalie Dormer, atriz da série "Game of Thrones".			  ', 'millajovovichresidentevil6.jpg', '2017-04-02 23:01:11', 'Deise Mota'),
(24, 'James Gunn', 'O diretor americano James Gunn, de "Guardiões da Galáxia" (2014), vai vir ao Brasil para participar da Comic Con Experience (CCPX), anunciou a Disney nesta quinta-feira (10).\r\nNa feira de cultura pop, ele vai participar de um painel em 3 de dezembro no qual vai falar sobre "Guardiões da Galáxia Vol. 2" (assista ao trailer abaixo), que estreia em 5 de maio de 2017.\r\nA CCXP acontece na São Paulo Expo do dia 1º ao dia 4 de dezembro.\r\nA sequência do filme de super-heróis da Marvel retoma a história da equipe formada por Chris Pratt, Zoe Saldana e Dave Bautista. Além deles, Vin Diesel e Bradley Cooper voltam como dubladores de Groot e Rocket, respectivamente.', 'guardioes6.jpg', '2017-04-02 23:02:21', 'Caio'),
(25, 'Mulher Maravilha', 'A Warner divulgou neste sábado (23) na Comic-Con International: San Diego 2016 o primeiro trailer de "Mulher Maravilha", que estreia no dia 1º de junho de 2017. A protagonista é vivida pela atriz e modelo israelense Gal Gadot, de 31 anos. Quem dirige é Patty Jenkins ("Monster: Desejo assassino" e "The Killing").\r\nO evento em que ocorreu o lançamento é considerado um dos principais da cultura pop do mundo.\r\nA apresentação era uma aposta da DC Comics, que mais tarde mostrou os trailers de "Liga da Justiça" e "Esquadrão Suicida". O estúdio apostava muito nesta Comic-Con após a morna recepção de "Batman vs Superman: A Origem da Justiça", que apesar juntar dois dos super-heróis mais populares da história não conseguiu satisfazer a crítica e o público.', 'mulher-maravilha-poster.jpg', '2017-04-02 23:03:38', 'Raimundo'),
(26, 'Leonard Nimoy', 'O filho do ator Leonard Nimoy, que ficou famoso ao atuar como Spock na série e nos filmes de "Star trek" ("Jornada nas estrelas"), virá ao Brasil para lançar o documentário sobre o pai, "For the love of Spock". Adam Nimoy dirigiu a produção, e participará da terceira edição da Comic Con Experience (CCXP) em São Paulo no dia 2 de dezembro para o lançamento.\r\nAlém de Adam, o produtor do filme, David Zappone, estará presente no evento. Os dois também participarão do painel especial sobre o legado de Leonard e em comemoração dos 50 anos de "Star trek", além de exibir o longa.\r\nNarrado por Zachary Quinto, ator que interpreta a versão do icônico vulcano nos novos filmes, "For the love of Spock" entrevista atores e equipes que passaram pela franquia para analisar a carreira e trabalho de Leonard, que morreu em 2015.', 'ftlostrailerstill5.jpg', '2017-04-02 23:05:20', 'Spock'),
(27, 'Criador de Pokémon Go', 'O criador do game para celulares "Pokémon Go" recebeu tratamento de celebridade no último dia da feira de cultura pop Comic-Con, em San Diego, no domingo (24), ao discutir o futuro do game com o público.\r\nJohn Hanke, fundador da Niantic Labs e desenvolvedor de "Pokémon Go", foi recebido com aplausos de mais de 6,5 mil fãs no palco reservado para apresentações de estrelas de estúdios de cinema e redes de televisão.\r\nHanke disse que a popularidade mundial do jogo, que incorpora os personagens do universo Pokémon, da Nintendo, com o mundo real por meio das tecnologias de realidade aumentada e de mapas do Google, foi alucinante.\r\nO jogo foi lançado em 6 de julho e evoluiu a partir do game Ingress, também da Niantic, que Hanke disse que ganhou popularidade após o lançamento de "Pokémon Go".', '2016-07-15t053159z_334113759_s1aetpqxcpaa_rtrmadp_3_nintendo-pokemon-niantic.jpg', '2017-04-02 23:07:19', 'Alexandre'),
(28, 'Old Man Logan', 'Depois de nove anos o brasileiro Mike Deodato Jr. volta a ilustrar Logan, o Wolverine, personagem icônico da franquia X-Men. Ao mesmo tempo em que é lançado o encerramento da atual série de filmes do personagem nesta quinta-feira (2), Mike foi convocado para ilustrar a continuidade da vida de Wolverine nos quadrinhos, o Velho Logan (Old Man Logan, em inglês). A 25ª edição do Velho Logan com as ilustrações do paraibano estarão disponíveis primeiro nos Estados Unidos, a partir de junho.\r\n“É muito bom poder voltar a ilustrar o Wolverine. Passei nove anos longe dele, ilustrando os Vingadores Sombrios [Dark Avengers], mas mesmo assim sempre fazia algum desenho de Logan”, conta Deodato.\r\nEle disse que nunca ilustrou o Velho Logan, mas o considera um “personagem marcante desde novo, então ele mais velho vai apresentar mais cicatrizes e histórias, o que fica bem mais interessante”.', 'img_2223.jpg', '2017-04-02 23:08:53', 'Ludy'),
(29, 'Super Joaquim', 'Familiares do bebê Joaquim, de 7 meses, que sofre de uma doença rara e degenerativa que paralisa a musculatura do corpo, realizaram neste sábado (11) um pedágio na zona sul de Ribeirão Preto (SP) para arrecadar fundos para o tratamento da doença, avaliado em R$ 3 milhões.\r\nO grupo colocou à venda camisetas personalizadas do "Super Joaquim", retratando a criança como se fosse um herói da Marvel Comics, e fez uma uma mobilização no cruzamento das avenidas Presidente Vargas e João Fiúsa desde a manhã até o início da tarde.', 'dsc_0040.jpg', '2017-04-02 23:11:19', 'Stanley'),
(30, 'King Kong', 'A Warner revelou neste sábado (23) na Comic-Con International: San Diego 2016 o primeiro trailer de novo filme do "King-Kong", chamado de "Kong: Skull Island".\r\nA estreia mundial será em março de 2017 e o filme tem no elenco Tom Hiddleston, Samuel L. Jackson, Brie Larson, John Goodman e John C. Reilly', 'kong_2.jpg', '2017-04-02 23:12:50', 'Eve'),
(31, 'Comic-Con', ' Comic-Con DiaryComic-Con DiaryComic-Con DiaryComic-Con DiaryComic-Con DiaryComic-Con Diary	Alterado', 'comiccon_wide-7d5ed33de8a8d68b5c00406a73c94e534479bba1-s800-c85.jpg', '2017-04-02 23:14:54', 'Fabrícia Galibi'),
(32, 'Comic-Con', 'É oficial, de 4 e 7 de dezembro, o Centro de Exposições Imigrantes em São Paulo vai receber a edição brasileira do Comic-Con, o evento geek mais conhecido do mundo que se realiza todos os anos em San Diego e em versões menores noutros estados americanos.\r\n\r\nO evento brasilero será de menor dimensão e vai chamar-se Comic-Con Experience tendo previsto 60 mil visitantes em contraste com os 150 mil da versão americana. Os ingressos começam a ser vendidos em abril mas ainda não foram revelados os preços.', 'thww5.jpg', '2017-04-02 23:16:40', 'Carlos Augusto');


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
